### ISSUE TITLE
Add instructions on docs about the best AVD config to run tests

### ISSUE THREAD

**Issue by GabriellCosta** [natura-cosmeticos/natds-android#36]
Hello

I'am trying to run the sample tests (screenshot tests) but the following error appear's

```
E/TestRunner: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NoSuchMethodException: android.view.ViewRootImpl.<init> [class android.content.Context, class android.view.Display]
        at com.facebook.testing.screenshot.internal.ScreenshotImpl.runCallableOnUiThread(ScreenshotImpl.java:346)
        at com.facebook.testing.screenshot.internal.ScreenshotImpl.storeBitmap(ScreenshotImpl.java:167)
        at com.facebook.testing.screenshot.internal.ScreenshotImpl.record(ScreenshotImpl.java:271)
        at com.facebook.testing.screenshot.internal.RecordBuilderImpl.record(RecordBuilderImpl.java:152)
        at com.natura.android.sample.test.submenu.SubmenuActivityTest.checkView(SubmenuActivityTest.kt:48)
        at com.natura.android.sample.test.submenu.SubmenuActivityTest.verifySubmenuWhenIsEnabled(SubmenuActivityTest.kt:27)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
        at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
        at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: android.view.ViewRootImpl.<init> [class android.content.Context, class android.view.Display]
        at com.facebook.testing.screenshot.WindowAttachment.generateAttachInfo(WindowAttachment.java:230)
        at com.facebook.testing.screenshot.WindowAttachment.dispatchAttach(WindowAttachment.java:89)
        at com.facebook.testing.screenshot.internal.ScreenshotImpl.storeBitmap(ScreenshotImpl.java:183)
        at com.facebook.testing.screenshot.internal.ScreenshotImpl.access$000(ScreenshotImpl.java:50)
        at com.facebook.testing.screenshot.internal.ScreenshotImpl$2.call(ScreenshotImpl.java:171)
        at com.facebook.testing.screenshot.internal.ScreenshotImpl$2.call(ScreenshotImpl.java:168)
        at com.facebook.testing.screenshot.internal.ScreenshotImpl$3.run(ScreenshotImpl.java:328)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    	at com.andro
```

My setup:

* Linux

* python 2.7.17

* git 2.20.1

* git-lfs/2.10.0 (GitHub; linux amd64; go 1.13.4)

* Master branch

I tried with `connectedAndroidTest`, `:sample:verifyDebugAndroidTestScreenshotTest`, android studio run, `:sample:connectedDebugAndroidTest`

obs: the unit test in `designsystem` has failed too

**Comment by jimmyandrade** [comment]
@GabriellCosta 

How are you doing? We apologize for the delay in responding to you. We are from the new team that curates the Design System. Can you tell us if the problem is still happening? Feel free to get in touch.

cc @mlcsouza

**Comment by jimmyandrade** [comment]
@GabriellCosta Happy to hear that you managed to resolve this issue on your side. 😄 

And, yes, it's a great idea to include instructions to avoid this problem on our side.
In this case, we can leave this issue open until we include some instructions in the documentation.

/cc @mlcsouza
